******************* Revision Control System *****************************
*
* $Author: lozben $
* =======================================================================
*
* $Date: 91/01/03 15:06:08 $
* =======================================================================
*
* =======================================================================
*
* Revision 3.0  91/01/03  15:06:08  lozben
* New generation VDI
*
* Revision 2.1  89/02/21  17:17:57  kbad
* *** TOS 1.4  FINAL RELEASE VERSION ***
*
* Revision 1.1  87/11/20  15:14:08  lozben
* Initial revision
*
*************************************************************************

#include "config.h"
#include "vdidefs.h"
#include "asmdefs.h"
#include "tosvars.inc"

#include "lineaequ.inc"

#if BLITTER_SUPPORT

		xdef	st_blaster

st_blaster:	rts

#endif
