monout_306_OPTIMIZE=0
monout_206_OPTIMIZE=1
monout_208_OPTIMIZE=1
monout_OPTIMIZE=$(monout_$(TOSVERSION)_OPTIMIZE)

text_100_OPTIMIZE=0
text_OPTIMIZE=$(text_$(TOSVERSION)_OPTIMIZE)

seedfill_306_OPTIMIZE=0
seedfill_206_OPTIMIZE=1
seedfill_208_OPTIMIZE=1
seedfill_OPTIMIZE=$(seedfill_$(TOSVERSION)_OPTIMIZE)
