deskact_OPTIMIZE=0
deskapp1_OPTIMIZE=0
deskapp3_OPTIMIZE=0
deskbind_OPTIMIZE=0
deskdir_OPTIMIZE=0
deskdisk_OPTIMIZE=0
deskinf_OPTIMIZE=0
deskins_OPTIMIZE=0
deskmisc_OPTIMIZE=0
deskpref_OPTIMIZE=0
deskshow_OPTIMIZE=0
deskstor_OPTIMIZE=0
desktop_OPTIMIZE=0
deskwin_OPTIMIZE=0
deskfun_OPTIMIZE=0
deskif_OPTIMIZE=0
desksupp_OPTIMIZE=0

rainbow_ASFLAGS = -n
