/*	GEMBIND.C		5/30/90 - 5/31/90	Derek Mui	*/
/*	Translate back from assembly code dated 4/26/90			*/
/*	O.K			6/25/90			D.Mui		*/
/*	Release acc wait at appl_exit	7/13/90		D.Mui		*/
/*	Remove appl_init and appl_exit	4/3/91		D.Mui		*/
/*	Add mouse restore	5/8/91			D.Mui		*/
/*	Remove mouse restore	6/14/91			D.Mui		*/
/*	Add ob_sysvar		7/7/92			D.Mui		*/
/*	Change binding for wm_get	7/8/92		D.Mui		*/
/*	Add sub menu functions		7/8/92		D.Mui		*/

#include "aes.h"
#include "gemlib.h"
#include "crysbind.h"
#include "taddr.h"
#include "gemrsc.h"
#include "gsxdefs.h"


/* int16_t gl_dspcnt; */ /* unused */

VOIDPTR ad_rso;

extern VOIDPTR maddr; /* hmpf */

uint16_t crysbind PROTO((int16_t opcode, intptr_t pglobal, uint16_t *int_in, int16_t *int_out, VOIDPTR *addr_in));


#define CONTROL LLGET(pcrys_blk)
#define GLOBAL LLGET(pcrys_blk+4)
#define INT_IN LLGET(pcrys_blk+8)
#define INT_OUT LLGET(pcrys_blk+12)
#define ADDR_IN LLGET(pcrys_blk+16)
#define ADDR_OUT LLGET(pcrys_blk+20)


/*
 * Don't look at the ugly asm code below.
 * Apparently, this was a stupid attempt by Atari
 * to save a few bytes.
 */
#define ASM_HACKS 0
#ifdef __ALCYON__
#if (TOSVERSION <= 0x104)
#undef ASM_HACKS
#define ASM_HACKS 1
#endif
#endif

/* 206de: 00e1686c */
/* 306de: 00e1a2d2 */
/* 104de: 00fdf10c */
/* 106de: 00e20a78 */
uint16_t crysbind(P(int16_t) opcode, P(intptr_t) pglobal, P(uint16_t *) int_in, P(int16_t *) int_out, P(VOIDPTR *) addr_in)
PP(int16_t opcode;)
PP(register intptr_t pglobal;)
#if (BINEXACT & (AESVERSION < 0x330)) | ASM_HACKS
PP(uint16_t *int_in;)
PP(int16_t *int_out;)
PP(VOIDPTR *addr_in;)
#else
PP(register uint16_t *int_in;)
PP(register int16_t *int_out;)
PP(register VOIDPTR *addr_in;)
#endif
{
	intptr_t tmparm;
	intptr_t lbuparm;
	intptr_t lmaddr;
	LPTREE tree;
	register int16_t ret;
	MFORM *mform;

	ret = TRUE;

	UNUSED(lmaddr);
	UNUSED(mform);
	
	switch (opcode)
	{
	/* Application Manager  */
	case APPL_INIT:
#if ASM_HACKS
		/* WTF? no way that the code below has been generated by C-code */
		asm("movea.l    d7,a0");
		asm("move.l     #$01400001,(a0)+");
		asm("movea.l    _rlr,a1")
		asm("move.w     28(a1),(a0)");
		asm("movea.l    d7,a0");
		asm("adda.l     #20,a0");
		asm("move.w     _gl_nplanes,(a0)+");
		asm("move.l     #_D,(a0)+");
		asm("move.w     _gl_bvdisk,(a0)+");
		asm("move.w     _gl_bvhard,(a0)");
		ret = rlr->p_pid;
		asm("bra        L9999")
#else
		LLSET(pglobal, (((long)AESVERSION) << 16) | 1);
		LWSET(pglobal + 4, rlr->p_pid);
		LWSET(pglobal + 20, gl_nplanes);
		LLSET(pglobal + 22, &D);
		LWSET(pglobal + 26, gl_bvdisk);
		LWSET(pglobal + 28, gl_bvhard);
		ret = rlr->p_pid;
		break;
#endif
#if ASM_HACKS
		/* WTF? no way that the code below has been generated by C-code */
	case APPL_READ:
		asm("moveq.l    #1,d0");
		asm("bra.s      L9700")
	case APPL_WRITE:
		asm("moveq.l    #2,d0");
		asm("L9700:");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("move.w     d0,-(a7)");
		asm("jsr _ap_rdwr");
		asm("bra        L9996")
#else
	case APPL_READ:
		/* BUG: ignores the return value of ap_rdwr() */
		ap_rdwr(AQRD, AP_RWID, AP_LENGTH, AP_PBUFF);
		break;
	case APPL_WRITE:
		/* BUG: ignores the return value of ap_rdwr() */
		ap_rdwr(AQWRT, AP_RWID, AP_LENGTH, AP_PBUFF);
		break;
#endif
	case APPL_FIND:
		ret = ap_find(AP_PNAME);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case APPL_TPLAY:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr _ap_tplay");
		asm("bra        L9995")
#else
		ap_tplay((intptr_t)AP_TBUFFER, AP_TLENGTH, AP_TSCALE);
		break;
#endif
	case APPL_TRECORD:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr _ap_trecd");
		asm("move.w     d0,d6");
		asm("bra        L9997")
#else
		ret = ap_trecd((intptr_t)AP_TBUFFER, AP_TLENGTH);
		break;
#endif
	case APPL_EXIT:
#if ASM_HACKS
		mn_clsda();
		if (rlr->p_qindex)
		{
			asm("move.l     #_D+7072,(a7)"); /* D.g_valstr */
			asm("movea.l    _rlr,a0");
			asm("move.w     54(a0),-(a7)");
			asm("move.w     28(a0),-(a7)");
			asm("move.w     #1,-(a7)");
			asm("jsr        _ap_rdwr");
			asm("addq.l     #6,a7");
		}
		all_run();
		asm("bra        L9999")
#else
		ap_exit();
		break;
#endif

	/* Event Manager */
	case EVNT_KEYBD:
		ret = ev_keybd();
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case EVNT_BUTTON:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     2(a0),-(a7)");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _ev_button");
		asm("move.w     d0,d6");
		asm("bra        L9996")
#else
		ret = ev_button(B_CLICKS, B_MASK, B_STATE, &EV_MX);
		break;
#endif
	case EVNT_MOUSE:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("jsr        _ev_mouse");
		asm("move.w     d0,d6");
		asm("bra        L9997")
#else
		ret = ev_mouse((MOBLK *)&MO_FLAGS, &EV_MX);
		break;
#endif
	case EVNT_MESAG:
		ret = ev_mesag(ME_PBUFF);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case EVNT_TIMER:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("move.w     2(a0),-(a7)");
		asm("jsr        _ev_timer");
		asm("move.w     d0,d6");
		asm("bra        L9998")
#else
		ret = ev_timer(HW(T_HICOUNT) | LW(T_LOCOUNT));
		break;
#endif
	case EVNT_MULTI:
		if (MU_FLAGS & MU_TIMER)
		{
#if ASM_HACKS
			asm("movea.l    14(a6),a0");
			asm("clr.l      d0");
			asm("move.w     30(a0),d0");
			asm("swap       d0");
			asm("move.w     28(a0),d0");
			asm("move.l     d0,-4(a6)");
#else
			tmparm = HW(MT_HICOUNT) + LW(MT_LOCOUNT);
#endif
		}
#if !BINEXACT
		else
			tmparm = 0; /* BUG: using undefined value */
#endif
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("clr.l      d0");
		asm("move.w     2(a0),d0");
		asm("swap       d0");
		asm("clr.l      d1");
		asm("move.w     4(a0),d1");
		asm("lsl.w      #8,d1");
		asm("move.w     6(a0),d2");
		asm("or.w       d2,d1");
		asm("and.l      #$0000FFFF,d1");
		asm("or.l       d1,d0");
		asm("move.l     d0,-8(a6)");
		
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("move.l     -8(a6),-(a7)");
		asm("move.l     -4(a6),-(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("addi.l     #18,(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("addq.l     #8,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _ev_multi");
		asm("move.w     d0,d6");
		asm("adda.l     #22,a7");
		asm("bra        L9999")
#else
		lbuparm = HW(MB_CLICKS) | LW((MB_MASK << 8) | MB_STATE);
		ret = ev_multi(MU_FLAGS, (MOBLK *)&MMO1_FLAGS, (MOBLK *)&MMO2_FLAGS, tmparm, lbuparm, MME_PBUFF, &EV_MX);
		break;
#endif
	case EVNT_DCLICK:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ev_dclick");
		asm("move.w     d0,d6");
		asm("bra        L9997")
#else
		ret = ev_dclick(EV_DCRATE, EV_DCSETIT);
		break;
#endif

	/* Menu Manager */
	case MENU_BAR:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _mn_bar");
		asm("bra        L9997")
#else
		mn_bar((LPTREE)MM_ITREE, SHOW_IT);
		break;
#endif
	case MENU_ICHECK:
#if ASM_HACKS
		asm("clr.l      -(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     2(a0),-(a7)");
		asm("move.w     #4,-(a7)");
		asm("move.w     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _do_chg");
		asm("bra        L9992")
#else
		do_chg((LPTREE)MM_ITREE, ITEM_NUM, CHECKED, CHECK_IT, FALSE, FALSE);
		break;
#endif
	case MENU_IENABLE:
#if ASM_HACKS
		asm("clr.w      (a7)");
		asm("movea.l    14(a6),a0");
		asm("clr.w      d0");
		asm("move.w     (a0),d0");
		asm("and.w      #$8000,d0");
		asm("bne.s      L9800");
		asm("clr.w      -(a7)");
		asm("bra.s      L9801");
		asm("L9800:");
		asm("move.w     #1,-(a7)");
		asm("L9801:");
		asm("movea.l    14(a6),a0");
		asm("tst.w      2(a0)");
		asm("beq.s      L9802");
		asm("clr.w      -(a7)");
		asm("bra.s      L9803");
		asm("L9802:");
		asm("move.w     #1,-(a7)");
		asm("L9803:");
		asm("move.w     #8,-(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("andi.w     #$7FFF,(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _do_chg");
		asm("bra        L9993")
#else
		do_chg((LPTREE)MM_ITREE, (ITEM_NUM & 0x7FFF), DISABLED, !ENABLE_IT, ((ITEM_NUM & 0x8000) != 0x0), FALSE);
		break;
#endif
	case MENU_TNORMAL:
#if ASM_HACKS
		asm("move.l     #$00010001,-(a7)");
		asm("movea.l    14(a6),a0");
		asm("tst.w      2(a0)");
		asm("beq.s      L9810");
		asm("clr.w      -(a7)");
		asm("bra.s      L9811");
		asm("L9810:");
		asm("move.w     #1,-(a7)");
		asm("L9811:");
		asm("move.w     #1,-(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _do_chg");
		asm("bra        L9992")
#else
		do_chg((LPTREE)MM_ITREE, TITLE_NUM, SELECTED, !NORMAL_IT, TRUE, TRUE);
		break;
#endif
	case MENU_TEXT:
/*
 * AES #34 - menu_text - Replaces the text of a menu item.
 */
		tree = (LPTREE)MM_ITREE;
#if ASM_HACKS
		asm("move.l     4(a0),(a7)");
		asm("movea.l    #12,a0");
		asm("movea.l    14(a6),a1");
		asm("clr.w      d1");
		asm("move.w     (a1),d1");
		asm("mulu.w     #24,d1");
		asm("add.l      -16(a6),d1");
		asm("move.l     0(a0,d1.l),-(a7)");
		asm("jsr        _LSTCPY");
		asm("bra        L9997")
#else
		LSTCPY((VOIDPTR)LLGET(OB_SPEC(ITEM_NUM)), MM_PTEXT);
		break;
#endif
	case MENU_REGISTER:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _mn_register");
		asm("move.w     d0,d6");
		asm("bra        L9998")
#else
		ret = mn_register(MM_PID, MM_PSTR);
		break;
#endif
	
	/* Object Manager   */
	case OBJC_ADD:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_add");
		asm("bra        L9995")
#else
		ob_add((LPTREE)OB_TREE, OB_PARENT, OB_CHILD);
		break;
#endif
	case OBJC_DELETE:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_delete");
		asm("bra        L9997")
#else
		ob_delete((LPTREE)OB_TREE, OB_DELOB);
		break;
#endif
	case OBJC_DRAW:
		gsx_sclip((GRECT *)&OB_XCLIP);
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_draw");
		asm("bra        L9995")
#else
		ob_draw((LPTREE)OB_TREE, OB_DRAWOB, OB_DEPTH);
		break;
#endif
	case OBJC_FIND:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     4(a0),-(a7)");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_find");
		asm("move.w     d0,d6");
		asm("bra        L9993")
#else
		ret = ob_find((LPTREE)OB_TREE, OB_STARTOB, OB_DEPTH, OB_MX, OB_MY);
		break;
#endif
	case OBJC_OFFSET:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.l     18(a6),-(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_offset");
		asm("bra        L9994")
#else
		ob_offset((LPTREE)OB_TREE, OB_OBJ, &OB_XOFF, &OB_YOFF);
		break;
#endif
	case OBJC_ORDER:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_order");
		asm("bra        L9995")
#else
		ob_order((LPTREE)OB_TREE, OB_OBJ, OB_NEWPOS);
		break;
#endif
	case OBJC_EDIT:
		OB_ODX = OB_IDX;
#if ASM_HACKS
		asm("move.w     6(a1),(a7)");
		asm("move.l     a0,-(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_edit");
		asm("move.w     d0,d6");
		asm("bra        L9992")
#else
		ret = ob_edit((LPTREE)OB_TREE, OB_OBJ, OB_CHAR, &OB_ODX, OB_KIND);
		break;
#endif
	case OBJC_CHANGE:
		gsx_sclip((GRECT *)&OB_XCLIP);
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     12(a0),-(a7)");
		asm("move.w     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_change");
		asm("bra        L9994")
#else
		ob_change((LPTREE)OB_TREE, OB_DRAWOB, OB_NEWSTATE, OB_REDRAW);
		break;
#endif

	/* Form Manager */
	case FORM_DO:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _fm_do");
		asm("move.w     d0,d6");
		asm("bra        L9997")
#else
		ret = fm_do((LPTREE)FM_FORM, FM_START);
		break;	
#endif
	case FORM_DIAL:
#if ASM_HACKS
		asm("move.l     14(a6),(a7)");
		asm("addi.l     #10,(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _fm_dial");
		asm("bra        L9996")
#else
		fm_dial(FM_TYPE, (GRECT *)&FM_IX, (GRECT *)&FM_X);
		break;
#endif
	case FORM_ALERT:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _fm_alert");
		asm("move.w     d0,d6");
		asm("bra        L9998")
#else
		ret = fm_alert(FM_DEFBUT, FM_ASTRING);
		break;
#endif
	case FORM_ERROR:
		ret = fm_error(FM_ERRNUM);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case FORM_CENTER:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _ob_center");
		asm("bra        L9997")
#else
		ob_center((LPTREE)FM_FORM, (GRECT *)&FM_XC);
		break;
#endif
	case FORM_KEYBD:
		gsx_sclip(&gl_rfull);
		FM_OCHAR = FM_ICHAR;
#if ASM_HACKS
		asm("move.w     4(a1),2(a0)");
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("move.l     18(a6),-(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.w     (a1),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _fm_keybd");
		asm("move.w     d0,d6");
		asm("bra        L9994")
#else
		FM_ONXTOB = FM_INXTOB;
		ret = fm_keybd((LPTREE)FM_FORM, FM_OBJ, &FM_OCHAR, &FM_ONXTOB);
		break;
#endif
	case FORM_BUTTON:
		gsx_sclip(&gl_rfull);
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _fm_button");
		asm("move.w     d0,d6");
		asm("bra        L9995")
#else
		ret = fm_button((LPTREE)FM_FORM, FM_OBJ, FM_CLKS, &FM_ONXTOB);
		break;
#endif
	
	/* Graphics Manager */
	case GRAF_RUBBOX:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.l     18(a6),-(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     4(a0),-(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _gr_rubbox");
		asm("bra        L9993")
#else
		gr_rubbox(GR_I1, GR_I2, GR_I3, GR_I4, &GR_O1, &GR_O2);
		break;
#endif
	case GRAF_DRAGBOX:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.l     18(a6),-(a7)");
		asm("addq.l     #2,(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("addq.l     #8,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     4(a0),-(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _gr_dragbox");
		asm("bra        L9991")
#else
		gr_dragbox(GR_I1, GR_I2, GR_I3, GR_I4, (GRECT *)&GR_I5, &GR_O1, &GR_O2);
		break;
#endif
	case GRAF_MBOX:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     10(a0),(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     6(a0),-(a7)");
		asm("move.l     2(a0),-(a7)");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _gr_movebox");
		asm("bra        L9994")
#else
		gr_movebox(GR_I1, GR_I2, GR_I3, GR_I4, GR_I5, GR_I6);
		break;
#endif
#if ASM_HACKS
	case GRAF_GROWBOX:
		asm("movea.l    #_gr_growbox,a0");
		asm("bra.s      L9820");
	case GRAF_SHRINKBOX:
		asm("movea.l    #_gr_shrinkbox,a0");
		asm("L9820:");
		asm("move.l     14(a6),(a7)");
		asm("addq.l     #8,(a7)");
		asm("move.l     14(a6),-(a7)");
		asm("jsr        (a0)");
		asm("bra        L9997")
#else
	case GRAF_GROWBOX:
		gr_growbox((GRECT *)&GR_I1, (GRECT *)&GR_I5);
		break;
	case GRAF_SHRINKBOX:
		gr_shrinkbox((GRECT *)&GR_I1, (GRECT *)&GR_I5);
		break;
#endif
	case GRAF_WATCHBOX:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     6(a0),(a7)");
		asm("move.l     2(a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _gr_watchbox");
		asm("move.w     d0,d6");
		asm("bra        L9995")
#else
		ret = gr_watchbox(GR_TREE, GR_OBJ, GR_INSTATE, GR_OUTSTATE);
		break;
#endif
	case GRAF_SLIDEBOX:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     4(a0),(a7)");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _gr_slidebox");
		asm("move.w     d0,d6");
		asm("bra        L9995")
#else
		ret = gr_slidebox((LPTREE)GR_TREE, GR_PARENT, GR_OBJ, GR_ISVERT);
		break;
#endif
	case GRAF_HANDLE:
/*
 * AES #77 - graf_handle - Obtain the VDI handle of the AES workstation. 
 */
#if ASM_HACKS
		asm("movea.l    18(a6),a0");
		asm("addq.l     #2,a0");
		asm("move.w     _gl_wchar,(a0)+");
		asm("move.w     _gl_hchar,(a0)+");
		asm("move.w     _gl_wbox,(a0)+");
		asm("move.w     _gl_hbox,(a0)");
		ret = gl_handle;
		asm("bra        L9999")
#else
		GR_WCHAR = gl_wchar;
		GR_HCHAR = gl_hchar;
		GR_WBOX = gl_wbox;
		GR_HBOX = gl_hbox;
		ret = gl_handle;
		break;
#endif
	case GRAF_MOUSE:
		if (maddr)
		{
			ctlmouse(FALSE);
#if ASM_HACKS
			asm("st         _maddr");
#else
			maddr = (VOIDPTR)1;
#endif
		}
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("cmpi.w     #255,(a0)");
		asm("bls.s      L9831");
		asm("cmpi.w     #256,(a0)");
		asm("bne.s      L9830");
		asm("jsr         _gsx_fmoff");
		asm("bra.s      L9834");
		asm("L9830:");
		asm("cmpi.w     #257,(a0)");
		asm("bne.s      L9834");
		asm("jsr        _gsx_mon");
		asm("bra.s      L9834");
		asm("L9831:");
		asm("cmpi.w     #255,(a0)");
		asm("beq.s      L9832");
		asm("pea.l      -12(a6)");
		asm("move.w     (a0),-(a7)");
		asm("addq.w     #3,(a7)");
		asm("move.w     #14,-(a7)");
		asm("move.l     _ad_sysglo,-(a7)");
		asm("jsr        _rs_gaddr");
		asm("adda.l     #12,a7");
		asm("movea.l    -12(a6),a0");
		asm("move.l     (a0),-12(a6)");
		asm("bra.s      L9833");
		asm("L9832:");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-12(a6)");
		asm("L9833:");
		asm("move.l     -12(a6),(a7)");
		asm("jsr        _gsx_mfset");
		asm("L9834:");
		asm("tst.b      _maddr");
		asm("beq        L9999");
		asm("move.w     #1,(a7)");
		asm("jsr        _ctlmouse");
		asm("bra        L9999");
#else
		/* gr_mouse */
		if (GR_MNUMBER > USER_DEF)
		{
			if (GR_MNUMBER == M_OFF)
				gsx_moff();
			else if (GR_MNUMBER == M_ON)
				gsx_mon();
		} else
		{
			VOIDPTR grmaddr;
			
			if (GR_MNUMBER != USER_DEF)			/* set new mouse form   */
			{
				/* BUG: gsx_mfset will crash if this fails because number is out of range... */
				rs_gaddr(ad_sysglo, R_BIPDATA, MICE0 + GR_MNUMBER, &grmaddr);
				grmaddr = (MFORM *)LLGET((intptr_t)grmaddr);
			} else
			{
				grmaddr = (MFORM *)LLGET((intptr_t)GR_MADDR);
			}

			gsx_mfset(grmaddr);
		}
		if (maddr)
			ctlmouse(TRUE);
		break;
#endif
	case GRAF_MKSTATE:
#if ASM_HACKS
		asm("move.l     18(a6),d0");
		asm("move.l     d0,(a7)");
		asm("addq.l     #8,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #6,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #2,(a7)");
		asm("jsr        _gr_mkstate");
		asm("move.w     d0,d6");
		asm("bra        L9993")
#else
		ret = gr_mkstate(&GR_MX, &GR_MY, &GR_MSTATE, &GR_KSTATE);
		/* BUG: the asm version of gr_mkstate returns -1,
		   and the call should always return TRUE */
		break;
#endif
	
	/* Scrap Manager */
	case SCRP_READ:
		sc_read(SC_PATH);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case SCRP_WRITE:
		sc_write(SC_PATH);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	
	/* File Selector Manager */
#if ASM_HACKS
	case FSEL_INPUT:
		asm("move.l     _ad_fsel,-(a7)");
		asm("movea.l    22(a6),a0");
		asm("bra.s      L9840");
	case FSEL_EXINPUT:
		asm("movea.l    22(a6),a0");
		asm("move.l     8(a0),-(a7)");
		asm("L9840:");
		asm("move.l     18(a6),-(a7)");
		asm("addq.l     #2,(a7)");
		asm("move.l     4(a0),-(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _fs_input");
		asm("move.w     d0,d6");
		asm("bra        L9991");
#else
	case FSEL_INPUT:
		ret = fs_input(FS_IPATH, FS_ISEL, &FS_BUTTON, ad_fsel);
		break;
	case FSEL_EXINPUT:
		ret = fs_input(FS_IPATH, FS_ISEL, &FS_BUTTON, FS_LABEL);
		break;
#endif

	/* Window Manager */
	case WIND_CREATE:
#if ASM_HACKS
		asm("move.l     14(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _wm_create");
		asm("move.w     d0,d6");
		asm("bra        L9998");
#else
		ret = wm_create(WM_KIND, (GRECT *)&WM_WX);
		break;
#endif
	case WIND_OPEN:
#if ASM_HACKS
		asm("move.l     14(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _wm_open");
		asm("bra        L9998");
#else
		wm_open(WM_HANDLE, (GRECT *)&WM_WX);
		break;
#endif
	case WIND_CLOSE:
		wm_close(WM_HANDLE);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case WIND_DELETE:
		wm_delete(WM_HANDLE);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif

	case WIND_GET:
#if ASM_HACKS
		asm("move.l     18(a6),(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _wm_get");
		asm("bra        L9997");
#else
		/* BUG: ignores return value */
		wm_get(WM_HANDLE, WM_WFIELD, &WM_OX);
		break;
#endif
	case WIND_SET:
#if ASM_HACKS
		asm("move.l     14(a6),(a7)");
		asm("addq.l     #4,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _wm_set");
		asm("bra        L9997");
#else
		wm_set(WM_HANDLE, WM_WFIELD, (int16_t *)&WM_IX); /* BUG: ignores return value */
		break;
#endif
	case WIND_FIND:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _wm_find");
		asm("move.w     d0,d6");
		asm("bra        L9997");
#else
		ret = wm_find(WM_MX, WM_MY);
		break;
#endif
	case WIND_UPDATE:
		/* BUG: ignores return value */
		wm_update(WM_BEGUP);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case WIND_CALC:
#if ASM_HACKS
		asm("move.l     18(a6),d0");
		asm("move.l     d0,(a7)");
		asm("addq.l     #8,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #6,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #4,(a7)");
		asm("move.l     d0,-(a7)");
		asm("addq.l     #2,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     8(a0),-(a7)");
		asm("move.l     4(a0),-(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _wm_calc");
		asm("adda.l     #24,a7");
		asm("bra        L9999");
#else
		wm_calc(WM_WCTYPE, WM_WCKIND, WM_WCIX, WM_WCIY, WM_WCIW, WM_WCIH, &WM_WCOX, &WM_WCOY, &WM_WCOW, &WM_WCOH);
		break;
#endif

	case WIND_NEW:
		ret = wm_new();
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif

	/* Resource Manager */
	case RSRC_LOAD:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),(a7)");
		asm("move.l     d7,-(a7)");
		asm("jsr        _rs_load");
		asm("move.w     d0,d6");
		asm("bra        L9997");
#else
		ret = rs_load(pglobal, RS_PFNAME);
		break;
#endif
	case RSRC_FREE:
		ret = rs_free(pglobal);
#if ASM_HACKS
		asm("bra        L9999")
#else
		break;
#endif
	case RSRC_GADDR:
#if ASM_HACKS
		asm("move.l     #_ad_rso,(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("move.l     d7,-(a7)");
		asm("jsr        _rs_gaddr");
		asm("move.w     d0,d6");
		asm("bra        L9995");
#else
		ret = rs_gaddr(pglobal, RS_TYPE, RS_INDEX, &ad_rso);
		break;
#endif
	case RSRC_SADDR:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("move.l     d7,-(a7)");
		asm("jsr        _rs_saddr");
		asm("move.w     d0,d6");
		asm("bra        L9995");
#else
		ret = rs_saddr(pglobal, RS_TYPE, RS_INDEX, RS_INADDR);
		break;
#endif
	case RSRC_OBFIX:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _rs_obfix");
		asm("move.w     d0,d6");
		asm("bra        L9997");
#else
		ret = rs_obfix((LPTREE)RS_TREE, RS_OBJ);
		break;
#endif
	
	/* Shell Manager */
	case SHEL_READ:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     4(a0),(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _sh_read");
		asm("move.w     d0,d6");
		asm("bra        L9997");
#else
		ret = sh_read(SH_PCMD, SH_PTAIL);
		break;
#endif
	case SHEL_WRITE:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     4(a0),(a7)");
		asm("move.l     (a0),-(a7)");
		asm("movea.l    14(a6),a0");
		asm("move.l     2(a0),-(a7)");
		asm("move.w     (a0),-(a7)");
		asm("jsr        _sh_write");
		asm("move.w     d0,d6");
		asm("dc.w       0x6000,L9994-*-2");
#else
		ret = sh_write(SH_DOEX, SH_ISGR, SH_ISCR, SH_PCMD, SH_PTAIL);
		break;
#endif
	case SHEL_GET:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _sh_get");
		asm("move.w     d0,d6");
		asm("bra.s      L9997");
#else
		ret = sh_get(SH_PBUFFER, SH_LEN);
		break;
#endif
	case SHEL_PUT:
#if ASM_HACKS
		asm("movea.l    14(a6),a0");
		asm("move.w     (a0),(a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _sh_put");
		asm("move.w     d0,d6");
		asm("bra.s      L9997");
#else
		ret = sh_put(SH_PDATA, SH_LEN);
		break;
#endif
	case SHEL_FIND:
#if ASM_HACKS
		asm("clr.l      (a7)");
		asm("movea.l    22(a6),a0");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _sh_find");
		asm("move.w     d0,d6");
		asm("bra.s      L9997");
		
#else
		ret = sh_find(SH_PATH, NULL);
		break;
#endif
	case SHEL_ENVRN:
#if ASM_HACKS
		asm("movea.l    22(a6),a0");
		asm("move.l     4(a0),(a7)");
		asm("move.l     (a0),-(a7)");
		asm("jsr        _sh_envrn");
		asm("move.w     d0,d6");
		asm("bra.s      L9997");
#else
		ret = sh_envrn(SH_PATH, SH_SRCH);
		break;
#endif

	default:
#if ASM_HACKS
		asm("Ldefault:");
		asm("move.l     #1,-(a7)");
		asm("move.w     #0,-(a7)");
		asm("move.w     _no_aes,-(a7)");
		asm("jsr        _fm_show");
		asm("addq.w     #8,a7");
		ret = -1;
		/*
		 * Note: this break will generate a branch to the end of the switch,
		 * which will be the first of the tst.w instructions below,
		 * and thus be wrong. It is hacked in the Makefile by replacing
		 * it to bra L9999
		 */
		break;
#else
		fm_show(ALRTNOFUNC, NULL, 1); /* why not use no_aes here? */
		ret = -1;
		break;
#endif
	}
#if ASM_HACKS
	asm("L9991:");
	asm("tst.w      (a7)+");
	asm("L9992:");
	asm("tst.w      (a7)+");
	asm("L9993:");
	asm("tst.w      (a7)+");
	asm("L9994:");
	asm("tst.w      (a7)+");
	asm("L9995:");
	asm("tst.w      (a7)+");
	asm("L9996:");
	asm("tst.w      (a7)+");
	asm("L9997:");
	asm("tst.w      (a7)+");
	asm("L9998:");
	asm("tst.w      (a7)+");
	asm("L9999:");
#endif
	return ret;
}

#if (TOSVERSION <= 0x104) & BINEXACT
asm("data");
asm("dc.l Ldefault");
asm("text");
#endif


/*
 *	Routine that copies input parameters into local buffers,
 *	calls the appropriate routine via a case statement, copies
 *	return parameters from local buffers, and returns to the
 *	routine.
 */
/* 306de: 00e1ad0a */
/* 206de: 00e172a4 */
/* 104de: 00fdf894 */
/* 106de: 00e2133a */
asm("    .globl xif");
asm("xif: .text");
VOID xif(P(intptr_t) pcrys_blk)
PP(intptr_t pcrys_blk;)
{
	uint16_t control[C_SIZE];
	uint16_t int_in[I_SIZE];
	int16_t int_out[O_SIZE];
	VOIDPTR addr_in[AI_SIZE];

	LWCOPY(ADDR(control), (VOIDPTR)CONTROL, C_SIZE);

	if (IN_LEN)
		LWCOPY(ADDR(int_in), (VOIDPTR)INT_IN, IN_LEN);

	if (AIN_LEN)
	{
#if ASM_HACKS
		asm("clr.w      d0");
		asm("move.w     -2(a6),d0");
		asm("lsl.w      #1,d0");
		asm("move.w     d0,(a7)");
		asm("movea.l    #16,a0");
		asm("movea.l    8(a6),a1");
		asm("move.l     0(a0,a1.l),-(a7)");
		asm("pea.l      -62(a6)");
		asm("jsr        _LWCOPY");
		asm("addq.l     #8,a7");
		
#else
		LWCOPY(ADDR(addr_in), (VOIDPTR)ADDR_IN, AIN_LEN * (sizeof(VOIDPTR) / 2));
#endif
	}

#if ASM_HACKS
	asm("pea.l      -62(a6)");
	asm("pea.l      -54(a6)");
	asm("pea.l      -40(a6)");
	asm("movea.l    #4,a0");
	asm("movea.l    8(a6),a1");
	asm("move.l     0(a0,a1.l),-(a7)");
	asm("move.w     -8(a6),-(a7)");
	asm("bsr        _crysbind");
	asm("adda.l     #18,a7");
	asm("move.w     d0,-54(a6)");
#else
	int_out[0] = crysbind(OP_CODE, GLOBAL, int_in, int_out, addr_in);
#endif
	
	/*
	 * long standing BUG: nobody sets OUT_LEN here, so this depends
	 * on the language binding used.
	 * It should be AES however which tells how many output parameters were supplied,
	 * just like VDI does.
	 */
	if (OUT_LEN)
		LWCOPY((VOIDPTR)INT_OUT, int_out, OUT_LEN);

	/*
	 * rsrc_gaddr() is the only function that returns an address parameter
	 */
	if (OP_CODE == RSRC_GADDR)
		LLSET(ADDR_OUT, ad_rso);
}
