[00fe78c0] dc.l $00fe1b3c            ; F000 ; gsx_1code AES
[00fe78c4] dc.l $00fd4a42            ; F004 ; bb_fill AES
[00fe78c8] dc.l $00fd4abe            ; F008 ; gsx_tcalc AES
[00fe78cc] dc.l $00fd43dc            ; F00C ; gr_just AES
[00fe78d0] dc.l $00fd4b24            ; F010 ; gsx_tblt AES
[00fe78d4] dc.l $00fd4700            ; F014 ; gsx_attr AES
[00fe78d8] dc.l $00fd47e8            ; F018 ; gsx_blt AES
[00fe78dc] dc.l $00fe1dbe            ; F01C ; gsx_moff AES
[00fe78e0] dc.l $00fd4388            ; F020 ; gr_inside AES
[00fe78e4] dc.l $00fd4796            ; F024 ; gsx_box AES
[00fe78e8] dc.l $00fe1dda            ; F028 ; gsx_mon AES
[00fe78ec] dc.l $00fe1e5a            ; F02C ; avst_clip AES
[00fe78f0] dc.l $00fe1e46            ; F030 ; av_pline AES
[00fe78f4] dc.l $00fe1dda            ; F034 ; gsx_mon; duplicate; unused AES
[00fe78f8] dc.l $00fe5bba            ; F038 ; gsx2 AES
[00fe78fc] dc.l $00fe1dbe            ; F03C ; gsx_moff; duplicate; unused AES
[00fe7900] dc.l $00fe1ebe            ; F040 ; avrt_cpyfm AES
[00fe7904] dc.l $00fe1eac            ; F044 ; avro_cpyfm AES
[00fe7908] dc.l $00fe1dda            ; F048 ; gsx_mon; duplicate; unused AES
[00fe790c] dc.l $00fe1ed4            ; F04C ; avr_trnfm AES
[00fe7910] dc.l $00fe1b1e            ; F050 ; gsx_ncode AES
[00fe7914] dc.l $00fe1e6e            ; F054 ; avst_height AES
[00fe7918] dc.l $00fe1b3c            ; F058 ; gsx_1code; duplicate; unused AES
[00fe791c] dc.l $00fe1ede            ; F05C ; avsl_width AES
[00fe7920] dc.l $00fe1b3c            ; F060 ; gsx_1code; duplicate; unused AES
[00fe7924] dc.l $00fe1e9c            ; F064 ; avr_recfl AES
[00fe7928] dc.l $00fe5c46            ; F068 ; LBWMOV AES
[00fe792c] dc.l $00fe1e6e            ; F06C ; avst_height; duplicate; unused AES
[00fe7930] dc.l $00fe1e46            ; F070 ; av_pline; duplicate; unused AES
[00fe7934] dc.l $00fe1b3c            ; F074 ; gsx_1code; duplicate; unused AES
[00fe7938] dc.l $00fe24d2            ; F078 ; mn_clsda AES
[00fe793c] dc.l $00fdf958            ; F07C ; ap_rdwr AES
[00fe7940] dc.l $00fd3ce6            ; F080 ; all_run AES
[00fe7944] dc.l $00fdce42            ; F084 ; dsptch AES
[00fe7948] dc.l $00fdfd20            ; F088 ; ev_multi AES
[00fe794c] dc.l $00fdfc2c            ; F08C ; ev_button AES
[00fe7950] dc.l $00fdffe6            ; F090 ; ev_dclick AES
[00fe7954] dc.l $00fdb032            ; F094 ; desk_wait DESKTOP
[00fe7958] dc.l $00fe0784            ; F098 ; fm_do AES
[00fe795c] dc.l $00fe08c6            ; F09C ; fm_dial AES
[00fe7960] dc.l $00fe036a            ; F0A0 ; fm_alert AES
[00fe7964] dc.l $00fe09cc            ; F0A4 ; fm_error AES
[00fe7968] dc.l $00fe2584            ; F0A8 ; ob_center AES
[00fe796c] dc.l $00fe1dbe            ; F0AC ; gsx_moff; duplicate AES
[00fe7970] dc.l $00fe3daa            ; F0B0 ; rs_gaddr AES
[00fe7974] dc.l $00fe1d84            ; F0B4 ; gsx_mfset AES
[00fe7978] dc.l $00fe1f60            ; F0B8 ; do_chg AES
[00fe797c] dc.l $00fe2348            ; F0BC ; mn_bar AES
[00fe7980] dc.l $00fd4612            ; F0C0 ; gsx_sclip AES
[00fe7984] dc.l $00fe36cc            ; F0C4 ; ob_change AES
[00fe7988] dc.l $00fe3d7c            ; F0C8 ; rs_free AES
[00fe798c] dc.l $00fe57d2            ; F0CC ; wm_get AES
[00fe7990] dc.l $00fe58ba            ; F0D0 ; wm_set AES
[00fe7994] dc.l $00fe5ad6            ; F0D4 ; wm_calc AES
[00fe7998] dc.l $00fd3cb8            ; F0D8 ; trap AES
[00fe799c] dc.l $00fd947e            ; F0DC ; fill_string DESKTOP
[00fe79a0] dc.l $00fd7cb6            ; F0E0 ; rsrc_gaddr DESKTOP
[00fe79a4] dc.l $00fe6a36            ; F0E4 ; bconws DESKTOP
[00fe79a8] dc.l $00fd7af6            ; F0E8 ; form_error DESKTOP
[00fe79ac] dc.l $00fe7592            ; F0EC ; trp14 AES
[00fe79b0] dc.l $00fe7582            ; F0F0 ; trp13 AES
[00fe79b4] dc.l $00fe0920            ; F0F4 ; fm_show AES
[00fe79b8] dc.l $00fe6988            ; F0F8 ; doui DESKTOP
[00fe79bc] dc.l $00fdf96a            ; F0FC ; ap_find AES
[00fe79c0] dc.l $00fdf998            ; F100 ; ap_tplay AES
[00fe79c4] dc.l $00fdfaee            ; F104 ; ap_trecd AES
[00fe79c8] dc.l $00fdfc1c            ; F108 ; ev_keybd AES
[00fe79cc] dc.l $00fdfc6c            ; F10C ; ev_mouse AES
[00fe79d0] dc.l $00fdfc98            ; F110 ; ev_mesag AES
[00fe79d4] dc.l $00fdfcbe            ; F114 ; ev_timer AES
[00fe79d8] dc.l $00fe5c32            ; F118 ; LSTCPY AES
[00fe79dc] dc.l $00fe250e            ; F11C ; mn_register AES
[00fe79e0] dc.l $00fe34f8            ; F120 ; ob_add AES
[00fe79e4] dc.l $00fe355c            ; F124 ; ob_delete AES
[00fe79e8] dc.l $00fe3366            ; F128 ; ob_draw AES
[00fe79ec] dc.l $00fe33e6            ; F12C ; ob_find AES
[00fe79f0] dc.l $00fe38c2            ; F130 ; ob_offset AES
[00fe79f4] dc.l $00fe35fc            ; F134 ; ob_order AES
[00fe79f8] dc.l $00fe29c4            ; F138 ; ob_edit AES
[00fe79fc] dc.l $00fe0588            ; F13C ; fm_keybd AES
[00fe7a00] dc.l $00fe0626            ; F140 ; fm_button AES
[00fe7a04] dc.l $00fe1932            ; F144 ; gr_rubbox AES
[00fe7a08] dc.l $00fe19ac            ; F148 ; gr_dragbox AES
[00fe7a0c] dc.l $00fe176e            ; F14C ; gr_movebox AES
[00fe7a10] dc.l $00fe1826            ; F150 ; gr_watchbox AES
[00fe7a14] dc.l $00fe1a66            ; F154 ; gr_slidebox AES
[00fe7a18] dc.l $00fde172            ; F158 ; ctlmouse AES
[00fe7a1c] dc.l $00fe1ad4            ; F15C ; gr_mkstate AES
[00fe7a20] dc.l $00fe3f9e            ; F160 ; sc_read AES
[00fe7a24] dc.l $00fe3fb2            ; F164 ; sc_write AES
[00fe7a28] dc.l $00fe0a8a            ; F168 ; fs_input AES
[00fe7a2c] dc.l $00fe56b2            ; F16C ; wm_create AES
[00fe7a30] dc.l $00fe578a            ; F170 ; wm_open AES
[00fe7a34] dc.l $00fe57a0            ; F174 ; wm_close AES
[00fe7a38] dc.l $00fe57b6            ; F178 ; wm_delete AES
[00fe7a3c] dc.l $00fe5a76            ; F17C ; wm_find AES
[00fe7a40] dc.l $00fe5a92            ; F180 ; wm_update AES
[00fe7a44] dc.l $00fe5b84            ; F184 ; wm_new AES
[00fe7a48] dc.l $00fe3f7a            ; F188 ; rs_load AES
[00fe7a4c] dc.l $00fe3dd6            ; F18C ; rs_saddr AES
[00fe7a50] dc.l $00fe39c2            ; F190 ; rs_obfix AES
[00fe7a54] dc.l $00fe3fc6            ; F194 ; sh_read AES
[00fe7a58] dc.l $00fe3ff2            ; F198 ; sh_write AES
[00fe7a5c] dc.l $00fe4038            ; F19C ; sh_get AES
[00fe7a60] dc.l $00fe4052            ; F1A0 ; sh_put AES
[00fe7a64] dc.l $00fe427c            ; F1A4 ; sh_find AES
[00fe7a68] dc.l $00fe414a            ; F1A8 ; sh_envrn AES
[00fe7a6c] dc.l $00fe5c5e            ; F1AC ; LWCOPY AES
[00fe7a70] dc.l $00fdf10c            ; F1B0 ; crysbind AES
[00fe7a74] dc.l $00fdf894            ; F1B4 ; xif; unused AES
[00fe7a78] dc.l $00fe17de            ; F1B8 ; gr_scale AES
[00fe7a7c] dc.l $00fe176e            ; F1BC ; gr_movebox; duplicate AES
[00fe7a80] dc.l $00fd4be8            ; F1C0 ; gsx_xcbox AES
[00fe7a84] dc.l $00fd4bbe            ; F1C4 ; gsx_xbox AES
[00fe7a88] dc.l $00fe172a            ; F1C8 ; gr_xor AES
[00fe7a8c] dc.l $00fe191c            ; F1CC ; gr_setup AES
[00fe7a90] dc.l $00fd4612            ; F1D0 ; gsx_sclip; duplicate; unused AES
[00fe7a94] dc.l $00fe3826            ; F1D4 ; ob_actxywh AES
[00fe7a98] dc.l $00fe36cc            ; F1D8 ; ob_change; duplicate; unused AES
[00fe7a9c] dc.l $00fdfd20            ; F1DC ; ev_multi; duplicate; unused AES
[00fe7aa0] dc.l $00fd4bbe            ; F1E0 ; gsx_xbox; duplicate; unused AES
[00fe7aa4] dc.l $00fd4bbe            ; F1E4 ; gsx_xbox; duplicate; unused AES
[00fe7aa8] dc.l $00fe1dbe            ; F1E8 ; gsx_moff; duplicate; unused AES
[00fe7aac] dc.l $00fe5d02            ; F1EC ; rc_equal; duplicate AES
[00fe7ab0] dc.l $00fe1874            ; F1F0 ; gr_stilldn AES
[00fe7ab4] dc.l $00fd4612            ; F1F4 ; gsx_sclip; duplicate; unused AES
[00fe7ab8] dc.l $00fd4700            ; F1F8 ; gsx_attr; duplicate; unused AES
[00fe7abc] dc.l $00fe5a92            ; F1FC ; wm_update; duplicate; unused AES
[00fe7ac0] dc.l $00fe1a48            ; F200 ; gr_clamp AES
[00fe7ac4] dc.l $00fe18e2            ; F204 ; gr_wait AES
[00fe7ac8] dc.l $00fe5a92            ; F208 ; wm_update; duplicate; unused AES
[00fe7acc] dc.l $00fe5a92            ; F20C ; wm_update; duplicate; unused AES
[00fe7ad0] dc.l $00fe191c            ; F210 ; gr_setup; duplicate; unused AES
[00fe7ad4] dc.l $00fe1a48            ; F214 ; gr_clamp; duplicate; unused AES
[00fe7ad8] dc.l $00fe1da0            ; F218 ; gsx_mxmy AES
[00fe7adc] dc.l $00fe5dda            ; F21C ; rc_constrain; duplicate AES
[00fe7ae0] dc.l $00fe18e2            ; F220 ; gr_wait; duplicate; unused AES
[00fe7ae4] dc.l $00fe5a92            ; F224 ; wm_update; duplicate; unused AES
[00fe7ae8] dc.l $00fe1da0            ; F228 ; gsx_mxmy; duplicate; unused AES
[00fe7aec] dc.l $00fe3876            ; F22C ; ob_relxywh AES
[00fe7af0] dc.l $00fe19ac            ; F230 ; gr_dragbox; duplicate AES
[00fe7af4] dc.l $00fe5bce            ; F234 ; mul_div AES
[00fe7af8] dc.l $00fd47ac            ; F238 ; gsx_fix AES
[00fe7afc] dc.l $00fdd11c            ; F23C ; dos_alloc; duplicate; unused AES
[00fe7b00] dc.l $00fdd188            ; F240 ; dos_free; duplicate AES
[00fe7b04] dc.l $00fd48ca            ; F244 ; gsx_start AES
[00fe7b08] dc.l $00fd47ac            ; F248 ; gsx_fix; duplicate; unused AES
[00fe7b0c] dc.l $00fe5e82            ; F24C ; strlen AES
[00fe7b10] dc.l $00fe5cc0            ; F250 ; rc_copy AES
[00fe7b14] dc.l $00fd4660            ; F254 ; gsx_gclip AES
[00fe7b18] dc.l $00fd7a28            ; F258 ; far_call DESKTOP
[00fe7b1c] dc.l $00fe6198            ; F25C ; ob_sst AES
[00fe7b20] dc.l $00fd4388            ; F260 ; gr_inside; duplicate; unused AES
[00fe7b24] dc.l $00fd467e            ; F264 ; gsx_chkclip AES
[00fe7b28] dc.l $00fe5c74            ; F268 ; LBCOPY AES
[00fe7b2c] dc.l $00fd4484            ; F26C ; gr_crack AES
[00fe7b30] dc.l $00fd45be            ; F270 ; gr_box AES
[00fe7b34] dc.l $00fd439c            ; F274 ; gr_rect AES
[00fe7b38] dc.l $00fe2ce2            ; F278 ; ob_format AES
[00fe7b3c] dc.l $00fd4446            ; F27C ; gr_gtext AES
[00fe7b40] dc.l $00fd44de            ; F280 ; gr_gicon AES
[00fe7b44] dc.l $00fe2d84            ; F284 ; ob_user AES
[00fe7b48] dc.l $00fd46ec            ; F288 ; gsx_cline AES
[00fe7b4c] dc.l $00fe6360            ; F28C ; get_par AES
[00fe7b50] dc.l $00fe38c2            ; F290 ; ob_offset; duplicate AES
[00fe7b54] dc.l $00fe625c            ; F294 ; everyobj AES
[00fe7b58] dc.l $00fe5cb4            ; F298 ; r_set AES
[00fe7b5c] dc.l $00fe5ccc            ; F29C ; inside AES
[00fe7b60] dc.l $00fe391a            ; F2A0 ; get_prev AES
[00fe7b64] dc.l $00fe355c            ; F2A4 ; ob_delete; duplicate AES
[00fe7b68] dc.l $00fe2dc6            ; F2A8 ; just_draw AES
[00fe7b6c] dc.l $00fe5f7e            ; F2AC ; fs_sset AES
[00fe7b70] dc.l $00fe600a            ; F2B0 ; inf_gindex; duplicate AES
[00fe7b74] dc.l $00fd7c66            ; F2B4 ; objc_find DESKTOP
[00fe7b78] dc.l $00fd6228            ; F2B8
[00fe7b7c] dc.l $00fd4f6e            ; F2BC ; app_mtoi DESKTOP
[00fe7b80] dc.l $00fda192            ; F2C0 ; do_redraw DESKTOP
[00fe7b84] dc.l $00fd7b1a            ; F2C4 ; graf_mouse DESKTOP
[00fe7b88] dc.l $00fd46c2            ; F2C8 ; gsx_pline AES
[00fe7b8c] dc.l $00fd5e3a            ; F2CC
[00fe7b90] dc.l $00fd7a36            ; F2D0 ; evnt_multi DESKTOP
[00fe7b94] dc.l $00fd5d7c            ; F2D4
[00fe7b98] dc.l $00fd4700            ; F2D8 ; gsx_attr; duplicate AES
[00fe7b9c] dc.l $00fd7bb0            ; F2DC ; graf_mkstate DESKTOP
[00fe7ba0] dc.l $00fe5dda            ; F2E0 ; rc_constrain AES
[00fe7ba4] dc.l $00fd5e9a            ; F2E4
[00fe7ba8] dc.l $00fd7d00            ; F2E8 ; wind_find DESKTOP
[00fe7bac] dc.l $00fdc3f4            ; F2EC
[00fe7bb0] dc.l $00fd5bfe            ; F2F0
[00fe7bb4] dc.l $00fd637e            ; F2F4
[00fe7bb8] dc.l $00fdb04c            ; F2F8
[00fe7bbc] dc.l $00fe5d18            ; F2FC ; rc_intersect AES
[00fe7bc0] dc.l $00fd7c8c            ; F300 ; objc_change DESKTOP
[00fe7bc4] dc.l $00fe5d82            ; F304 ; rc_union AES
[00fe7bc8] dc.l $00fd6452            ; F308
[00fe7bcc] dc.l $00fd7ba8            ; F30C ; graf_rubbox DESKTOP
[00fe7bd0] dc.l $00fd5f34            ; F310
[00fe7bd4] dc.l $00fd5c50            ; F314
[00fe7bd8] dc.l $00fd7a8e            ; F318 ; evnt_button DESKTOP
[00fe7bdc] dc.l $00fd4d3a            ; F31C ; hex_dig DESKTOP
[00fe7be0] dc.l $00fd4d76            ; F320 ; uhex_dig DESKTOP
[00fe7be4] dc.l $00fd4e14            ; F324 ; escan_str DESKTOP
[00fe7be8] dc.l $00fd4dac            ; F328 ; scan_2 DESKTOP
[00fe7bec] dc.l $00fd4e40            ; F32C ; escani_str DESKTOP
[00fe7bf0] dc.l $00fe5e38            ; F330 ; min AES
[00fe7bf4] dc.l $00fd7cd8            ; F334 ; shel_get DESKTOP
[00fe7bf8] dc.l $00fdcf4e            ; F338 ; isdrive AES
[00fe7bfc] dc.l $00fdcfea            ; F33C ; dos_open AES
[00fe7c00] dc.l $00fdd010            ; F340 ; dos_read AES
[00fe7c04] dc.l $00fdd16c            ; F344 ; dos_close AES
[00fe7c08] dc.l $00fe76de            ; F348 ; rom_ram AES
[00fe7c0c] dc.l $00fe652a            ; F34C ; cart_init AES
[00fe7c10] dc.l $00fd4cb0            ; F350 ; app_alloc DESKTOP
[00fe7c14] dc.l $00fd4e82            ; F354 ; inf_xdesk DESKTOP
[00fe7c18] dc.l $00fe5e54            ; F358 ; bfill AES
[00fe7c1c] dc.l $00fd4e5a            ; F35C ; save_sstr DESKTOP
[00fe7c20] dc.l $00fd4de4            ; F360 ; save_2 DESKTOP
[00fe7c24] dc.l $00fd55be            ; F364 ; app_reverse DESKTOP
[00fe7c28] dc.l $00fd7ce2            ; F368 ; shel_put DESKTOP
[00fe7c2c] dc.l $00fe5eae            ; F36C ; xstrpcpy AES
[00fe7c30] dc.l $00fdd184            ; F370 ; dos_create AES
[00fe7c34] dc.l $00fd6ad0            ; F374 ; dos_error DESKTOP
[00fe7c38] dc.l $00fdd014            ; F378 ; dos_write AES
[00fe7c3c] dc.l $00fdd17c            ; F37C ; dos_delete AES
[00fe7c40] dc.l $00fd9510            ; F380 ; up_allwin DESKTOP
[00fe7c44] dc.l $00fdd174            ; F384 ; dos_sdrv AES
[00fe7c48] dc.l $00fd9eca            ; F388
[00fe7c4c] dc.l $00fd9f56            ; F38C
[00fe7c50] dc.l $00fe5e24            ; F390 ; movs AES
[00fe7c54] dc.l $00fd79cc            ; F394 ; ap_bvset AES
[00fe7c58] dc.l $00fe6128            ; F398 ; wildcmp AES
[00fe7c5c] dc.l $00fe5e92            ; F39C ; streq AES
[00fe7c60] dc.l $00fd7b02            ; F3A0 ; form_center DESKTOP
[00fe7c64] dc.l $00fd7ad0            ; F3A4 ; form_dial DESKTOP
[00fe7c68] dc.l $00fd7c7a            ; F3A8 ; objc_draw DESKTOP
[00fe7c6c] dc.l $00fd7c52            ; F3AC ; objc_offset DESKTOP
[00fe7c70] dc.l $00fd68fa            ; F3B0 ; r_slash DESKTOP
[00fe7c74] dc.l $00fe5f1a            ; F3B4 ; fmt_str AES
[00fe7c78] dc.l $00fdd14a            ; F3B8 ; dos_avail AES
[00fe7c7c] dc.l $00fe74a6            ; F3BC ; do1_alert DESKTOP
[00fe7c80] dc.l $00fdd11c            ; F3C0 ; dos_alloc AES
[00fe7c84] dc.l $00fd81e8            ; F3C4
[00fe7c88] dc.l $00fe5fac            ; F3C8 ; inf_sset AES
[00fe7c8c] dc.l $00fd695a            ; F3CC ; fm_draw DESKTOP
[00fe7c90] dc.l $00fd7abc            ; F3D0 ; form_do DESKTOP
[00fe7c94] dc.l $00fe6034            ; F3D4 ; inf_what AES
[00fe7c98] dc.l $00fd6b16            ; F3D8
[00fe7c9c] dc.l $00fd75f2            ; F3DC
[00fe7ca0] dc.l $00fd6e40            ; F3E0
[00fe7ca4] dc.l $00fd795c            ; F3E4
[00fe7ca8] dc.l $00fd7316            ; F3E8
[00fe7cac] dc.l $00fd691c            ; F3EC ; do_finish DESKTOP
[00fe7cb0] dc.l $00fdd188            ; F3F0 ; dos_free AES
[00fe7cb4] dc.l $00fdd168            ; F3F4 ; dos_sdta AES
[00fe7cb8] dc.l $00fd6a5a            ; F3F8 ; xtr_mask DESKTOP
[00fe7cbc] dc.l $00fdcfb4            ; F3FC ; dos_sfirst AES
[00fe7cc0] dc.l $00fd7620            ; F400
[00fe7cc4] dc.l $00fe5ed0            ; F404 ; xstrpcat AES
[00fe7cc8] dc.l $00fd7730            ; F408
[00fe7ccc] dc.l $00fd7814            ; F40C
[00fe7cd0] dc.l $00fdd05c            ; F410 ; dos_mkdir AES
[00fe7cd4] dc.l $00fdcfde            ; F414 ; dos_snext AES
[00fe7cd8] dc.l $00fdd180            ; F418 ; dos_rmdir AES
[00fe7cdc] dc.l $00fdd102            ; F41C ; dos_rename AES
[00fe7ce0] dc.l $00fdd080            ; F420 ; dos_set AES
[00fe7ce4] dc.l $00fd6a7c            ; F424 ; rep_all DESKTOP
[00fe7ce8] dc.l $00fd6a9c            ; F428
[00fe7cec] dc.l $00fe5fd0            ; F42C ; fs_sget AES
[00fe7cf0] dc.l $00fe5f4e            ; F430 ; unfmt_str AES
[00fe7cf4] dc.l $00fd791e            ; F434
[00fe7cf8] dc.l $00fd6a0a            ; F438 ; drawclip DESKTOP
[00fe7cfc] dc.l $00fd69b6            ; F43C ; drawfld DESKTOP
[00fe7d00] dc.l $00fe752a            ; F440 ; fc_draw DESKTOP
[00fe7d04] dc.l $00fda0e0            ; F444 ; hd_win DESKTOP
[00fe7d08] dc.l $00fe6d20            ; F448 ; fc_format DESKTOP
[00fe7d0c] dc.l $00fe7126            ; F44C ; fc_copy DESKTOP
[00fe7d10] dc.l $00fe7592            ; F450 ; trp14int; duplicate AES
[00fe7d14] dc.l $00fe74ba            ; F454 ; fc_bar DESKTOP
[00fe7d18] dc.l $00fe73d0            ; F458 ; fc_rwsec DESKTOP
[00fe7d1c] dc.l $00fe5e44            ; F45C ; max AES
[00fe7d20] dc.l $00fe7408            ; F460 ; fc_clfix DESKTOP
[00fe7d24] dc.l $00fd8780            ; F464 ; desk_dfree DESKTOP
[00fe7d28] dc.l $00fd8d76            ; F468
[00fe7d2c] dc.l $00fdd164            ; F46C ; dos_gdrv AES
[00fe7d30] dc.l $00fd8fae            ; F470
[00fe7d34] dc.l $00fd8df2            ; F474
[00fe7d38] dc.l $00fd8f32            ; F478
[00fe7d3c] dc.l $00fe5ef8            ; F47C ; strchk AES
[00fe7d40] dc.l $00fe5ee4            ; F480 ; scasb AES
[00fe7d44] dc.l $00fd9056            ; F484
[00fe7d48] dc.l $00fe65c2            ; F488 ; cart_sfirst AES
[00fe7d4c] dc.l $00fd8f4a            ; F48C
[00fe7d50] dc.l $00fe65d4            ; F490 ; cart_snext AES
[00fe7d54] dc.l $00fd9118            ; F494
[00fe7d58] dc.l $00fe606a            ; F498 ; merge_str AES
[00fe7d5c] dc.l $00fd7ae6            ; F49C ; form_alert DESKTOP
[00fe7d60] dc.l $00fd7a0c            ; F4A0 ; appl_write DESKTOP
[00fe7d64] dc.l $00fdc4e6            ; F4A4
[00fe7d68] dc.l $00fd95c0            ; F4A8
[00fe7d6c] dc.l $00fd931a            ; F4AC
[00fe7d70] dc.l $00fda13c            ; F4B0
[00fe7d74] dc.l $00fdcd94            ; F4B4
[00fe7d78] dc.l $00fd7d48            ; F4B8 ; wind_set DESKTOP
[00fe7d7c] dc.l $00fdce1c            ; F4BC ; wind_grget DESKTOP
[00fe7d80] dc.l $00fd94c8            ; F4C0 ; send_msg DESKTOP
[00fe7d84] dc.l $00fd80aa            ; F4C4 ; xform_do DESKTOP
[00fe7d88] dc.l $00fd9572            ; F4C8
[00fe7d8c] dc.l $00fd6cce            ; F4CC
[00fe7d90] dc.l $00fd7774            ; F4D0
[00fe7d94] dc.l $00fda28a            ; F4D4
[00fe7d98] dc.l $00fd9768            ; F4D8
[00fe7d9c] dc.l $00fd5b36            ; F4DC
[00fe7da0] dc.l $00fd9848            ; F4E0
[00fe7da4] dc.l $00fdadb6            ; F4E4
[00fe7da8] dc.l $00fd8fe6            ; F4E8
[00fe7dac] dc.l $00fd9922            ; F4EC
[00fe7db0] dc.l $00fd9022            ; F4F0
[00fe7db4] dc.l $00fd9a6c            ; F4F4
[00fe7db8] dc.l $00fdcd06            ; F4F8
[00fe7dbc] dc.l $00fe6a5a            ; F4FC ; fc_start DESKTOP
[00fe7dc0] dc.l $00fd99e0            ; F500
[00fe7dc4] dc.l $00fd9b3c            ; F504
[00fe7dc8] dc.l $00fd9be0            ; F508
[00fe7dcc] dc.l $00fd7d6e            ; F50C ; my_itoa DESKTOP
[00fe7dd0] dc.l $00fd7e02            ; F510 ; fmt_date DESKTOP
[00fe7dd4] dc.l $00fd7db6            ; F514 ; fmt_time DESKTOP
[00fe7dd8] dc.l $00fd4660            ; F518 ; gsx_gclip AES
[00fe7ddc] dc.l $00fd7e58            ; F51C ; bldstring DESKTOP
[00fe7de0] dc.l $00fd4b24            ; F520 ; gsx_tblt; duplicate AES
[00fe7de4] dc.l $00fdb85a            ; F524 ; hd_msg DESKTOP
[00fe7de8] dc.l $00fe5fe8            ; F528 ; inf_fldset AES
[00fe7dec] dc.l $00fd8164            ; F52C
[00fe7df0] dc.l $00fd8284            ; F530
[00fe7df4] dc.l $00fdd178            ; F534 ; dos_chmod AES
[00fe7df8] dc.l $00fdd09a            ; F538 ; dos_label AES
[00fe7dfc] dc.l $00fd813e            ; F53C ; fmdodraw DESKTOP
[00fe7e00] dc.l $00fe600a            ; F540 ; inf_gindex AES
[00fe7e04] dc.l $00fd5596            ; F544 ; app_reschange DESKTOP
[00fe7e08] dc.l $00fe5e6a            ; F548 ; toupper AES
[00fe7e0c] dc.l $00fd4cfc            ; F54C ; app_free DESKTOP
[00fe7e10] dc.l $00fe5eba            ; F550 ; strscn AES
[00fe7e14] dc.l $00fd7c70            ; F554 ; objc_add DESKTOP
[00fe7e18] dc.l $00fdd1c4            ; F558 ; do_cdir AES
[00fe7e1c] dc.l $00fd7cce            ; F55C ; shel_write DESKTOP
[00fe7e20] dc.l $00fda2fa            ; F560
[00fe7e24] dc.l $00fdc652            ; F564
[00fe7e28] dc.l $00fda2a0            ; F568
[00fe7e2c] dc.l $00fda22c            ; F56C
[00fe7e30] dc.l $00fd7bca            ; F570 ; graf_growbox DESKTOP
[00fe7e34] dc.l $00fd7d2a            ; F574 ; wind_open DESKTOP
[00fe7e38] dc.l $00fd7cec            ; F578 ; wind_close DESKTOP
[00fe7e3c] dc.l $00fd7be0            ; F57C ; graf_shrinkbox DESKTOP
[00fe7e40] dc.l $00fe5d02            ; F580 ; rc_equal AES
[00fe7e44] dc.l $00fdc47a            ; F584
[00fe7e48] dc.l $00fdcdec            ; F588
[00fe7e4c] dc.l $00fdc430            ; F58C
[00fe7e50] dc.l $00fe1bb2            ; F590 ; gsx_escapes AES
[00fe7e54] dc.l $00fe66b2            ; F594 ; showfile DESKTOP
[00fe7e58] dc.l $00fda066            ; F598
[00fe7e5c] dc.l $00fdc2a6            ; F59C
[00fe7e60] dc.l $00fd9fde            ; F5A0
[00fe7e64] dc.l $00fda4b6            ; F5A4
[00fe7e68] dc.l $00fdc376            ; F5A8
[00fe7e6c] dc.l $00fd8e6c            ; F5AC
[00fe7e70] dc.l $00fda5d2            ; F5B0
[00fe7e74] dc.l $00fda900            ; F5B4
[00fe7e78] dc.l $00fda85e            ; F5B8
[00fe7e7c] dc.l $00fd82e8            ; F5BC
[00fe7e80] dc.l $00fd8538            ; F5C0
[00fe7e84] dc.l $00fdcd6a            ; F5C4
[00fe7e88] dc.l $00fd7d32            ; F5C8 ; wind_get DESKTOP
[00fe7e8c] dc.l $00fda3de            ; F5CC
[00fe7e90] dc.l $00fdac02            ; F5D0
[00fe7e94] dc.l $00fdac8c            ; F5D4
[00fe7e98] dc.l $00fe7582            ; F5D8 ; trp13; duplicate AES
[00fe7e9c] dc.l $00fe411e            ; F5DC ; sh_name AES
[00fe7ea0] dc.l $00fd7c2a            ; F5E0 ; menu_ienable DESKTOP
[00fe7ea4] dc.l $00fdb152            ; F5E4
[00fe7ea8] dc.l $00fda984            ; F5E8
[00fe7eac] dc.l $00fdaaa8            ; F5EC
[00fe7eb0] dc.l $00fd9624            ; F5F0
[00fe7eb4] dc.l $00fdad22            ; F5F4
[00fe7eb8] dc.l $00fdab74            ; F5F8
[00fe7ebc] dc.l $00fd7c1e            ; F5FC ; menu_icheck DESKTOP
[00fe7ec0] dc.l $00fdc09c            ; F600
[00fe7ec4] dc.l $00fd87dc            ; F604
[00fe7ec8] dc.l $00fd59a0            ; F608
[00fe7ecc] dc.l $00fd8a16            ; F60C
[00fe7ed0] dc.l $00fdb6f6            ; F610 ; hd_keybd DESKTOP
[00fe7ed4] dc.l $00fd8622            ; F614 ; desk_pref DESKTOP
[00fe7ed8] dc.l $00fdba7e            ; F618
[00fe7edc] dc.l $00fd55e8            ; F61C ; save_inf DESKTOP
[00fe7ee0] dc.l $00fe1bae            ; F620 ; av_hardcopy AES
[00fe7ee4] dc.l $00fd65ba            ; F624
[00fe7ee8] dc.l $00fd66ba            ; F628
[00fe7eec] dc.l $00fd9d76            ; F62C
[00fe7ef0] dc.l $00fdb318            ; F630 ; do_file DESKTOP
[00fe7ef4] dc.l $00fdb17c            ; F634
[00fe7ef8] dc.l $00fe75e0            ; F638 ; mediach AES
[00fe7efc] dc.l $00fdae56            ; F63C ; rb_start DESKTOP
[00fe7f00] dc.l $00fdaeae            ; F640 ; rb_stop DESKTOP
[00fe7f04] dc.l $00fdb3bc            ; F644
[00fe7f08] dc.l $00fdcc68            ; F648
[00fe7f0c] dc.l $00fdb470            ; F64C ; do_opt DESKTOP
[00fe7f10] dc.l $00fd7be8            ; F650 ; menu_tnormal DESKTOP
[00fe7f14] dc.l $00fdb774            ; F654 ; hd_menu DESTKOP
[00fe7f18] dc.l $00fda422            ; F658
[00fe7f1c] dc.l $00fdcbe0            ; F65C
[00fe7f20] dc.l $00fdcb5c            ; F660 ; srl_bar DESKTOP
[00fe7f24] dc.l $00fd7ab0            ; F664 ; evnt_dclick DESKTOP
[00fe7f28] dc.l $00fd7988            ; F668 ; ap_init AES
[00fe7f2c] dc.l $00fd7d0a            ; F66C ; wind_update DESKTOP
[00fe7f30] dc.l $00fd7d58            ; F670 ; wind_calc DESKTOP
[00fe7f34] dc.l $00fd5062            ; F674 ; read_inf DESKTOP
[00fe7f38] dc.l $00fd79e0            ; F678 ; ap_exit AES
[00fe7f3c] dc.l $00fdc184            ; F67C
[00fe7f40] dc.l $00fd8d90            ; F680
[00fe7f44] dc.l $00fd7c0e            ; F684 ; menu_bar DESKTOP
[00fe7f48] dc.l $00fdbb94            ; F688
[00fe7f4c] dc.l $00fdb5ea            ; F68C ; hd_button DESKTOP
[00fe7f50] dc.l $00fd598e            ; F690 ; set_defdrv DESKTOP
[00fe7f54] dc.l $00fd9e58            ; F694
[00fe7f58] dc.l $00fd7d14            ; F698 ; wind_create DESKTOP
[00fe7f5c] dc.l $00fd7cf6            ; F69C ; wind_delete DESKTOP
[00fe7f60] dc.l $00fd7c5c            ; F6A0 ; objc_order DESKTOP
[00fe7f64] dc.l $00fdc524            ; F6A4
[00fe7f68] dc.l $00fdc61c            ; F6A8
[00fe7f6c] dc.l $00fd4862            ; F6AC ; bb_screen AES
[00fe7f70] dc.l $00fdc988            ; F6B0
[00fe7f74] dc.l $00fdd4ee            ; F6B4 ; signal AES
[00fe7f78] dc.l $00fdfbfc            ; F6B8 ; ev_block AES
[00fe7f7c] dc.l $00fdeb0a            ; F6BC ; fpdnm AES
[00fe7f80] dc.l $00fe5c12            ; F6C0 ; i_lptr1 AES
[00fe7f84] dc.l $00fe1b1e            ; F6C4 ; gsx_ncode; duplicate AES
[00fe7f88] dc.l $00fe5c26            ; F6C8 ; m_lptr2 AES
[00fe7f8c] dc.l $00fde286            ; F6CC ; forkq AES
[00fe7f90] dc.l $00fdce56            ; F6D0 ; cli AES
[00fe7f94] dc.l $00fdce62            ; F6D4 ; sti AES
[00fe7f98] dc.l $00fded44            ; F6D8 ; aqueue AES
[00fe7f9c] dc.l $00fde5ce            ; F6DC ; amutex AES
[00fe7fa0] dc.l $00fde634            ; F6E0 ; dq AES
[00fe7fa4] dc.l $00fdd54a            ; F6E4 ; zombie AES
[00fe7fa8] dc.l $00fdd592            ; F6E8 ; evinsert AES
[00fe7fac] dc.l $00fde826            ; F6EC ; downorup AES
[00fe7fb0] dc.l $00fdd5c4            ; F6F0 ; takeoff AES
[00fe7fb4] dc.l $00fddbf8            ; F6F4 ; cre_aproc AES
[00fe7fb8] dc.l $00fdcf64            ; F6F8 ; pgmld AES
[00fe7fbc] dc.l $00fdec42            ; F6FC ; pstart AES
[00fe7fc0] dc.l $00fe65f4            ; F700 ; ld_cartacc AES
[00fe7fc4] dc.l $00fdd170            ; F704 ; dos_chdir AES
[00fe7fc8] dc.l $00fdda30            ; F708 ; sndcli AES
[00fe7fcc] dc.l $00fd413a            ; F70C ; pinit AES
[00fe7fd0] dc.l $00fe4e6c            ; F710 ; ap_sendmsg AES
[00fe7fd4] dc.l $00fe4bac            ; F714 ; w_bldactive AES
[00fe7fd8] dc.l $00fe4660            ; F718 ; w_getsize AES
[00fe7fdc] dc.l $00fe5c9c            ; F71C ; r_get AES
[00fe7fe0] dc.l $00fe194a            ; F720 ; gr_rubwind AES
[00fe7fe4] dc.l $00fe6514            ; F724 ; delay AES
[00fe7fe8] dc.l $00fddc8e            ; F728 ; ct_msgup AES
[00fe7fec] dc.l $00fddcc4            ; F72C ; hctl_window AES
[00fe7ff0] dc.l $00fe20b8            ; F730 ; mn_do AES
[00fe7ff4] dc.l $00fdea1a            ; F734 ; post_mouse AES
[00fe7ff8] dc.l $00fde876            ; F738 ; post_button AES
[00fe7ffc] dc.l $00fe4b64            ; F73C ; w_setactive AES
[00fe8000] dc.l $00fddf94            ; F740 ; hctl_button AES
[00fe8004] dc.l $00fddfce            ; F744 ; hctl_rect AES
[00fe8008] dc.l $00fe75a2            ; F748 ; getmouse AES
[00fe800c] dc.l $00fe1b3c            ; F74C ; gsx_1code; duplicate AES
[00fe8010] dc.l $00fe75c2            ; F750 ; putmouse AES
[00fe8014] dc.l $00fde07c            ; F754 ; ct_chgown AES
[00fe8018] dc.l $00fdce9a            ; F758 ; savestate AES
[00fe801c] dc.l $00fde2de            ; F75C ; disp_act AES
[00fe8020] dc.l $00fde306            ; F760 ; forker AES
[00fe8024] dc.l $00fde416            ; F764 ; chkkbd AES
[00fe8028] dc.l $00fdcef6            ; F768 ; switchto AES
[00fe802c] dc.l $00fdd64e            ; F76C ; iasync AES
[00fe8030] dc.l $00fdd614            ; F770 ; mwait AES
[00fe8034] dc.l $00fdd8ba            ; F774 ; aret AES
[00fe8038] dc.l $00fdfba2            ; F778 ; ev_rets AES
[00fe803c] dc.l $00fdfce4            ; F77C ; ev_mchk AES
[00fe8040] dc.l $00fdd978            ; F780 ; acancel AES
[00fe8044] dc.l $00fde684            ; F784 ; evremove AES
[00fe8048] dc.l $00fde59a            ; F788 ; tak_flag AES
[00fe804c] dc.l $00fe0020            ; F78C ; fm_strbrk AES
[00fe8050] dc.l $00fe389c            ; F790 ; ob_setxywh AES
[00fe8054] dc.l $00fe010c            ; F794 ; fm_parse AES
[00fe8058] dc.l $00fe0178            ; F798 ; fm_build AES
[00fe805c] dc.l $00fe1cb2            ; F79C ; bb_save AES
[00fe8060] dc.l $00fe1ce2            ; F7A0 ; bb_restore AES
[00fe8064] dc.l $00fe04fe            ; F7A4 ; find_obj AES
[00fe8068] dc.l $00fe37f4            ; F7A8 ; ob_fs AES
[00fe806c] dc.l $00fde1f4            ; F7AC ; take_ownership AES
[00fe8070] dc.l $00fde662            ; F7B0 ; fq AES
[00fe8074] dc.l $00fe16ac            ; F7B4 ; gr_growbox AES
[00fe8078] dc.l $00fe16e6            ; F7B8 ; gr_shrinkbox AES
[00fe807c] dc.l $00fe47fa            ; F7BC ; w_drawdesk AES
[00fe8080] dc.l $00fe50a8            ; F7C0 ; w_update AES
[00fe8084] dc.l $00fe3a0c            ; F7C4 ; rs_str AES
[00fe8088] dc.l $00fe1562            ; F7C8 ; r_sfiles AES
[00fe808c] dc.l $00fe0a3a            ; F7CC ; fs_back AES
[00fe8090] dc.l $00fe1224            ; F7D0 ; r_dir AES
[00fe8094] dc.l $00fdd048            ; F7D4 ; dos_gdir AES
[00fe8098] dc.l $00fe1da0            ; F7D8 ; gsx_mxmy; duplicate AES
[00fe809c] dc.l $00fe12f8            ; F7DC ; r_files AES
[00fe80a0] dc.l $00fe160e            ; F7E0 ; fs_draw AES
[00fe80a4] dc.l $00fe14b8            ; F7E4 ; r_sort AES
[00fe80a8] dc.l $00fdce6a            ; F7E8 ; hcli AES
[00fe80ac] dc.l $00fdd1ee            ; F7EC ; takecpm AES
[00fe80b0] dc.l $00fdce70            ; F7F0 ; hsti AES
[00fe80b4] dc.l $00fde144            ; F7F4 ; ictlmgr AES
[00fe80b8] dc.l $00fe77b6            ; F7F8 ; rsc_read AES
[00fe80bc] dc.l $00fddad4            ; F7FC ; ldaccs AES
[00fe80c0] dc.l $00fd4168            ; F800 ; pred_dinf AES
[00fe80c4] dc.l $00fe1b54            ; F804 ; gsx_init AES
[00fe80c8] dc.l $00fd4884            ; F808 ; gsx_trans AES
[00fe80cc] dc.l $00fdd22c            ; F80C ; takeerr AES
[00fe80d0] dc.l $00fe406c            ; F810 ; sh_tographic AES
[00fe80d4] dc.l $00fe1d64            ; F814 ; gsx_tick AES
[00fe80d8] dc.l $00fe549e            ; F818 ; wm_start AES
[00fe80dc] dc.l $00fe4344            ; F81C ; sh_main AES
[00fe80e0] dc.l $00fe779c            ; F820 ; rsc_free AES
[00fe80e4] dc.l $00fe1afc            ; F824 ; gsx_mfree AES
[00fe80e8] dc.l $00fdd224            ; F828 ; giveerr AES
[00fe80ec] dc.l $00fddb9a            ; F82C ; free_accs AES
[00fe80f0] dc.l $00fe1c2a            ; F830 ; gsx_wsclose AES
[00fe80f4] dc.l $00fdd1e2            ; F834 ; givecpm AES
[00fe80f8] dc.l $00fde6dc            ; F838 ; post_keybd AES
[00fe80fc] dc.l $00fe64be            ; F83C ; b_delay AES
[00fe8100] dc.l $00fe6450            ; F840 ; drawrat AES
[00fe8104] dc.l $00fdea52            ; F844 ; inorout AES
[00fe8108] dc.l $00fe3826            ; F848 ; ob_actxywh; duplicate AES
[00fe810c] dc.l $00fe2000            ; F84C ; menu_sr AES
[00fe8110] dc.l $00fe1f40            ; F850 ; rect_change AES
[00fe8114] dc.l $00fe1db6            ; F854 ; gsx_button AES
[00fe8118] dc.l $00fe1fc6            ; F858 ; menu_set AES
[00fe811c] dc.l $00fe2040            ; F85C ; menu_down AES
[00fe8120] dc.l $00fd46ec            ; F860 ; gsx_cline; duplicate AES
[00fe8124] dc.l $00fdec12            ; F864 ; p_nameit AES
[00fe8128] dc.l $00fe2764            ; F868 ; pxl_rect AES
[00fe812c] dc.l $00fe285c            ; F86C ; instr AES
[00fe8130] dc.l $00fe26fc            ; F870 ; find_pos AES
[00fe8134] dc.l $00fe2ce2            ; F874 ; ob_format; duplicate AES
[00fe8138] dc.l $00fe2938            ; F878 ; ob_stfn AES
[00fe813c] dc.l $00fe27d2            ; F87C ; curfld AES
[00fe8140] dc.l $00fe2978            ; F880 ; ob_delit AES
[00fe8144] dc.l $00fe289c            ; F884 ; check AES
[00fe8148] dc.l $00fe26a0            ; F888 ; ins_char AES
[00fe814c] dc.l $00fe2674            ; F88C ; scan_to_end AES
[00fe8150] dc.l $00fdeaba            ; F890 ; fapd AES
[00fe8154] dc.l $00fdeb9a            ; F894 ; getpd AES
[00fe8158] dc.l $00fdcf22            ; F898 ; psetup AES
[00fe815c] dc.l $00fdec7c            ; F89C ; doq AES
[00fe8160] dc.l $00fe3ec2            ; F8A0 ; do_rsfix AES
[00fe8164] dc.l $00fe3f6c            ; F8A4 ; rs_fixit AES
[00fe8168] dc.l $00fe3960            ; F8A8 ; fix_chpos AES
[00fe816c] dc.l $00fe3a6a            ; F8AC ; get_addr AES
[00fe8170] dc.l $00fe3a3e            ; F8B0 ; get_sub AES
[00fe8174] dc.l $00fe3d2e            ; F8B4 ; fix_long AES
[00fe8178] dc.l $00fe3d1c            ; F8B8 ; fix_ptr AES
[00fe817c] dc.l $00fe3d5c            ; F8BC ; rs_sglobe AES
[00fe8180] dc.l $00fdd032            ; F8C0 ; dos_lseek AES
[00fe8184] dc.l $00fe3b8e            ; F8C4 ; fix_trindex AES
[00fe8188] dc.l $00fe3c3c            ; F8C8 ; fix_tedinfo AES
[00fe818c] dc.l $00fe3cf8            ; F8CC ; fix_nptrs AES
[00fe8190] dc.l $00fe3be0            ; F8D0 ; fix_objects AES
[00fe8194] dc.l $00fe3e06            ; F8D4 ; rs_readit AES
[00fe8198] dc.l $00fdd204            ; F8D8 ; retake AES
[00fe819c] dc.l $00fe1b74            ; F8DC ; gsx_graphic AES
[00fe81a0] dc.l $00fd430c            ; F8E0 ; gsx_malloc AES
[00fe81a4] dc.l $00fe1c30            ; F8E4 ; ratinit AES
[00fe81a8] dc.l $00fe1dbe            ; F8E8 ; ratexit; duplicate AES
[00fe81ac] dc.l $00fe40b2            ; F8EC ; sh_draw AES
[00fe81b0] dc.l $00fe4254            ; F8F0 ; sh_search AES
[00fe81b4] dc.l $00fe4186            ; F8F4 ; sh_path AES
[00fe81b8] dc.l $00fe4094            ; F8F8 ; sh_toalpha AES
[00fe81bc] dc.l $00fe665a            ; F8FC ; cart_exec AES
[00fe81c0] dc.l $00fdbc88            ; F900 ; deskmain DESKTOP
[00fe81c4] dc.l $00fdd2cc            ; F904 ; dos_exec AES
[00fe81c8] dc.l $00fe45ea            ; F908 ; w_getxptr AES
[00fe81cc] dc.l $00fe4534            ; F90C ; w_obadd AES
[00fe81d0] dc.l $00fe46b6            ; F910 ; w_adjust AES
[00fe81d4] dc.l $00fe4760            ; F914 ; do_walk AES
[00fe81d8] dc.l $00fe4842            ; F918 ; w_cpwalk AES
[00fe81dc] dc.l $00fe4716            ; F91C ; w_hvassign AES
[00fe81e0] dc.l $00fe48e8            ; F920 ; w_barcalc AES
[00fe81e4] dc.l $00fe44ec            ; F924 ; w_nilit AES
[00fe81e8] dc.l $00fe4968            ; F928 ; w_bldbar AES
[00fe81ec] dc.l $00fe5464            ; F92C ; w_union AES
[00fe81f0] dc.l $00fe4f62            ; F930 ; w_mvfix AES
[00fe81f4] dc.l $00fe4ed8            ; F934 ; w_redraw AES
[00fe81f8] dc.l $00fe469e            ; F938 ; w_setsize AES
[00fe81fc] dc.l $00fe625c            ; F93C ; everyobj; duplicate AES
[00fe8200] dc.l $00fe4f94            ; F940 ; w_move AES
[00fe8204] dc.l $00fdee1e            ; F944 ; get_orect AES
[00fe8208] dc.l $00fe45a6            ; F948 ; w_setup AES
[00fe820c] dc.l $00fe514c            ; F94C ; draw_change AES
[00fe8210] dc.l $00fe5726            ; F950 ; wm_opcl AES
[00fe8214] dc.l $00fe5414            ; F954 ; w_owns AES
[00fe8218] dc.l $00fe1b08            ; F958 ; gsx_mret AES
[00fe821c] dc.l $00fe488e            ; F95C ; w_strgchg AES
[00fe8220] dc.l $00fde5f8            ; F960 ; unsync AES
[00fe8224] dc.l $00fdee3e            ; F964 ; mkpiece AES
[00fe8228] dc.l $00fdef1a            ; F968 ; brkrct AES
[00fe822c] dc.l $00fe6562            ; F96C ; cart_find AES
